import type { Metadata } from "next";
import { ContentstackProvider } from "@/contexts/ContentstackContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ContentstackProvider>{children}</ContentstackProvider>
      </body>
    </html>
  );
}
